udemy-learn-ruby-on-rails-from-scratch/myrubyblog/config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  get 'pages/resources'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'  
  get 'home/index'
    resources :posts
    resources :categories
    match '/about', :to => 'pages#about', via: :all
    match '/contact', :to => 'pages#contact', via: :all
    match '/resources', :to => 'pages#resources', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :all_categories
  helper_method :all_posts

  def all_categories
    @categories = Category.all
  end

  def all_posts
    @posts = Post.all
  end

end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @posts = @category.posts
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, :notice => "Your post have been save"
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path, :notice => "Your post have been updated"
    else
      render "edit"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => "Your post have been deleted"
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :author_id)
    end
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/helpers/application_helper.rb
module ApplicationHelper
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/helpers/categories_helper.rb
module CategoriesHelper
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/helpers/home_helper.rb
module HomeHelper
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/helpers/pages_helper.rb
module PagesHelper
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/helpers/posts_helper.rb
module PostsHelper
end

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/categories/edit.html.erb
<div class="post">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/categories/index.html.erb
<div class="post">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>

  <%= link_to 'New Category', new_category_path %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% all_categories.each do |category| %>
        <tr>
          <td><%= link_to(category.name,category) %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/categories/new.html.erb
<div class="post">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/categories/show.html.erb
<% if @posts.any? %>
  <% all_posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%= link_to post.title,post %></h2>
      <div class="entry"><%= post.body %></div>
        <div class="byline">
          <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
          <p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
        </div>
      </div>
  <% end %>
<% else %>
  <p style="color:#ffffff">There are no posts in this category</p>
<% end %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/home/index.html.erb
<% all_posts.each do |post| %>
  <div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
      <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
      <p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
    </div>
  </div>
<% end %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/layouts/application.html.erb
<%= render "partials/header" %>

  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="content">
          <div class="flash_message">
            <% flash.each do |key, value| %>
              <p><%= value%></p>
            <% end %>
          </div>
          <%= yield %>
          <div style="clear: both;">&nbsp;</div>
        </div>
            
        <%= render "partials/sidebar" %>

        <div style="clear: both;">&nbsp;</div>
      </div>
    </div>
  </div>

<%= render "partials/footer" %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/pages/about.html.erb
<div class="post">
  <h1>Pages#about</h1>
  <p>Find me in app/views/pages/about.html.erb</p>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/pages/contact.html.erb
<div class="post">
  <h1>Pages#contact</h1>
  <p>Find me in app/views/pages/contact.html.erb</p>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/pages/resources.html.erb
<div class="post">
  <h1>Pages#resources</h1>
  <p>Find me in app/views/pages/resources.html.erb</p>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/partials/_footer.html.erb
      <div id="footer">
        <p>&copy; 2019, My Ruby Blog - Sample Project - Learning Ruby on Rails</p>
      </div>
    </div>
  </body>
</html>
<%# 
</body>
</body>
</html> %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Ruby Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div id="wrapper">
      <div id="header-wrapper">
        <div id="header">
          <div id="logo">
            <h1><a href="#">My Ruby Blog</a></h1>
            <p>Learning Ruby on Rails</p>
          </div>
          <div id="menu">
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Blog", posts_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Resources", resources_path %></li>
            </ul>
          </div>
        </div>
      </div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/partials/_sidebar.html.erb
<div id="sidebar">
  <ul>
    <li>
			<div id="search" >
			  <form method="get" action="#">
				  <div>
					  <input type="text" name="s" id="search-text" value="" />
						<input type="submit" id="search-submit" value="GO" />
					</div>
				</form>
      </div>
      <div style="clear: both;">&nbsp;</div>
		</li>

    <li>
		  <h2>Get The Framework</h2>
			<p>You can download Ruby and/or Ruby on Rails for free right now
        <br />
          <a style="color:#D93544;" href="https://rubyonrails.org/" target="blank">GET IT NOW</a>
      </p>
		</li>

    <li>
		  <h2>Categories</h2>
			<ul>
			  <% all_categories.each do |category| %>
				  <li><%= link_to category.name,category_path(:id => category.id) %></li>
				<% end %>	
			</ul>
		</li>

    <li>
			<h2>Blogroll</h2>
			<ul>
			  <% all_posts.each do |post| %>
				  <li><%= link_to post.title,post_path(:id => post.id) %></li>
        <% end %>
		  </ul>
    </li>

  </ul>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="post">
  <%= form_for @post do |form| %>
    <p>
      <%= form.label :title %><br />
      <%= form.text_field :title %><br />
    </p>

    <p>
      <%= form.label :body %><br />
      <%= form.text_area :body %><br />
    </p>

    <p>
      <%= form.label :category_id %><br />
      <%= form.select :category_id, all_categories.collect {|category| [category.name, category.id]}, {:include_blank => "Select One"} %><br />
    </p>

    <button><h2><%= form.submit "Update Post" %></h2></button>

  <% end %>

  <button><h2><%= link_to "Cancel", post_path %></h2></button>

</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/posts/index.html.erb
<%= link_to "Add new post", new_post_path %>

<% all_posts.each do |post| %>
  <div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
      <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
      <p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
    </div>
  </div>
<% end %>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/posts/new.html.erb
<div class="post">
  <h1>New Post</h1>
  <%= form_for @post do |form| %>
    <p>
      <%= form.label :title %><br />
      <%= form.text_field :title %><br />
    </p>

    <p>
      <%= form.label :body %><br />
      <%= form.text_area :body %><br />
    </p>

    <p>
      <%= form.label :category_id %><br />
      <%= form.select :category_id, all_categories.collect {|category| [category.name, category.id]}, {:include_blank => "Select One"} %><br />
    </p>

    <button><h2><%= form.submit "Add Post" %></h2></button>

  <% end %>
</div>

udemy-learn-ruby-on-rails-from-scratch/myrubyblog/app/views/posts/show.html.erb
<div class="post">
  <h1> <%=@post.title %> </h1>

  <small> Create at: <%= @post.created_at.strftime("%d-%m-%y") %> </small>
  <br>
  <small> Category: <%= @post.category.name %> </small>

  <p> <%= @post.body %> </p>

  <%= link_to 'Edit', edit_post_path(@post) %>
  |
  <%= link_to 'Back', posts_path %>
  |
  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>